server:
  port: 6000
spring:
  application:
    name: kabigon-crowd-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.169.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
