server:
  port: 2000
spring:
  application:
    name: kabigon-crowd-mysql
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/project_crowd?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
logging:
  level:
   com.kabigon.crowd.mapper: debug
   com.kabigon.crowd.test: debug
ribbon:
  ReadTimeOut: 10000
  ConnectTimeout: 10000